---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dr-vm
spec:
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
      evictionStrategy: LiveMigrate
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: vm-1-pvc
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: redhat
              chpasswd: { expire: False }
          name: cloudinitdisk
