---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dr-vm
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
        app-svc: enisrest
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        resources:
          requests:
            memory: 4Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: vm-1-pvc
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: redhat
              chpasswd: { expire: False }
              rh_subscription:
                activation-key: bjeon-rhel
                org: '12685122'
              packages:
              - git
              - java-11-openjdk-devel
              - unzip
              - apr
              runcmd:
                - dnf install git java-11-openjdk-devel unzip apr -y
                - sudo -u cloud-user bash -c 'git clone https://github.com/jangminjun/egovframeworksample'
                - sudo -u cloud-user bash -c 'cd /home/cloud-user/egovframeworksample & unzip jws-5.8.0-application-server.zip'
                - sudo -u cloud-user bash -c 'cd /home/cloud-user/egovframeworksample & unzip jws-5.8.0-application-server-RHEL8-x86_64.zip'
                - sudo -u cloud-user bash -c 'cp /home/cloud-user/egovframeworksample/EnisRest -R /home/cloud-user/egovframeworksample/jws-5.8/tomcat'
                - sudo -u cloud-user bash -c '/home/cloud-user/egovframeworksample/jws-5.8/tomcat/bin/startup.sh'
          name: cloudinitdisk
